### ISSUE TITLE
`fatal error: nuitrack/Nuitrack.h: No such file or directory`

### ISSUE THREAD

**Issue by mitchmindtree** [freesig/nuitrack-rs#25]
Hey chap, I've followed the steps on the readme up to the cargo build section but for some reason the compiler  can't seem to find the Nuitrack.h header:

```
[mindtree@mindtree nuitrack-rs]$ cargo check                                                             
   Compiling nuitrack-rs v0.1.0 (/home/mindtree/programming/rust/nuitrack-rs)                             error: failed to run custom build command for `nuitrack-rs v0.1.0 (/home/mindtree/programming/rust/nuitrack-rs)`                                                                                                    process didn't exit successfully: `/home/mindtree/programming/rust/nuitrack-rs/target/debug/build/nuitrack-rs-afe654d88eb96f48/build-script-build` (exit code: 101)                                                
--- stdout      
TARGET = Some("x86_64-unknown-linux-gnu")                                                                
OPT_LEVEL = Some("0")                                                                                    
HOST = Some("x86_64-unknown-linux-gnu") 
CXX_x86_64-unknown-linux-gnu = None              
CXX_x86_64_unknown_linux_gnu = None            
HOST_CXX = None                                  
CXX = None                             
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None                      
CXXFLAGS = None                        
DEBUG = Some("true")                    
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64"
 "-I" "~/nuitrack/Nuitrack/include" "-I" "~/nuitrack/Nuitrack/include/middleware" "-I" "nui-helpers" "-std
=c++14" "-o" "/home/mindtree/programming/rust/nuitrack-rs/target/debug/build/nuitrack-rs-bb96774505b87c3d/
out/nui-helpers/helper.o" "-c" "nui-helpers/helper.cpp"
cargo:warning=In file included from nui-helpers/helper.cpp:1:
cargo:warning=nui-helpers/helper.hpp:2:10: fatal error: nuitrack/Nuitrack.h: No such file or directory
cargo:warning= #include <nuitrack/Nuitrack.h>                                                            
cargo:warning=          ^~~~~~~~~~~~~~~~~~~~~
cargo:warning=compilation terminated.                                                                    
exit code: 1                  

--- stderr                                        
thread 'main' panicked at 'Failed to build helper library: Error { kind: ToolExecError, message: "Command
\"c++\" \"-O0\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-g\" \"-fno-omit-frame-pointer\" \"-m64\" \"-I\" \"~/nuitrack/Nuitrack/include\" \"-I\" \"~/nuitrack/Nuitrack/include/middleware\" \"-I\" \"nui-helpers\" \"-std=c++14\" \"-o\" \"/home/mindtree/programming/rust/nuitrack-rs/target/debug/build/nuitrack-rs-bb96774505b87c3d/out/nui-helpers/helper.o\" \"-c\" \"nui-helpers/helper.cpp\" with args \"c++\" did not execute successfully (status code exit code: 1)." }', libcore/result.rs:1009:5                      
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace                                          
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49                                            
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook      
             at libstd/panicking.rs:227 
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390                                                                   
   6: rust_begin_unwind                                                                                   
             at libstd/panicking.rs:325                                                                   
   7: core::panicking::panic_fmt                       
             at libcore/panicking.rs:77                      
   8: core::result::unwrap_failed                                                                     
             at /rustc/0b9f19dff1347e29bf4362ab5a8fab84b43023b5/src/libcore/macros.rs:26                 
   9: <core::result::Result<T, E>>::expect   
             at /rustc/0b9f19dff1347e29bf4362ab5a8fab84b43023b5/src/libcore/result.rs:835                
  10: build_script_build::main
             at ./build.rs:39
  11: std::rt::lang_start::{{closure}}
             at /rustc/0b9f19dff1347e29bf4362ab5a8fab84b43023b5/src/libstd/rt.rs:74                      
  12: std::panicking::try::do_call                                                                        
             at libstd/rt.rs:59                                                                           
             at libstd/panicking.rs:310                                                                   
  13: __rust_maybe_catch_panic                                                                            
             at libpanic_unwind/lib.rs:102                                         
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289                        
             at libstd/panic.rs:398                          
             at libstd/rt.rs:58         
  15: std::rt::lang_start                        
             at /rustc/0b9f19dff1347e29bf4362ab5a8fab84b43023b5/src/libstd/rt.rs:74                      
  16: main                                       
  17: __libc_start_main                
  18: _start                      
```

This seems strange as I can see the header at that location. Here's the output of `tree ~/nuitrack`:

```
[mindtree@mindtree ~]$ tree ~/nuitrack/
/home/mindtree/nuitrack/         
├── Nuitrack              
│   ├── include      
│   │   ├── middleware           
│   │   │   └── DepthProviderAdapterAPI.h
│   │   └── nuitrack            
│   │       ├── capi       
│   │       │   ├── ColorSensor_CAPI.h
│   │       │   ├── DepthSensor_CAPI.h
│   │       │   ├── GestureRecognizer_CAPI.h
│   │       │   ├── HandTracker_CAPI.h
│   │       │   ├── IssueTracker_CAPI.h
│   │       │   ├── Nuitrack_CAPI.h
│   │       │   ├── NuitrackModule_CAPI.h
│   │       │   ├── Public_Nuitrack_CAPI.h
│   │       │   ├── SkeletonTracker_CAPI.h
│   │       │   └── UserTracker_CAPI.h
│   │       ├── middleware          
│   │       │   └── android      
│   │       │       ├── NuitrackManager.h
│   │       │       └── USBGateKeeper.h
│   │       ├── ModuleFunctions.h
│   │       ├── modules          
│   │       │   ├── ColorSensor.h 
│   │       │   ├── DepthSensor.h
│   │       │   ├── GestureRecognizer.h
│   │       │   ├── HandTracker.h
│   │       │   ├── HeaderOnlyAPI_Module.h
│   │       │   ├── Module.h
│   │       │   ├── NuitrackModule.h
│   │       │   ├── SkeletonTracker.h    
│   │       │   └── UserTracker.h
│   │       ├── Nuitrack.h
│   │       ├── types
│   │       │   ├── BoundingBox.h
│   │       │   ├── Color3.h
│   │       │   ├── DepthFrame.h
│   │       │   ├── Error.h
│   │       │   ├── Export.h
│   │       │   ├── FrameBorderIssue.h
│   │       │   ├── Frame.h
│   │       │   ├── GestureData.h
│   │       │   ├── Gesture.h
│   │       │   ├── Hand.h
│   │       │   ├── HandTrackerData.h
│   │       │   ├── Issue.h
│   │       │   ├── IssuesData.h
│   │       │   ├── ObjectData.h
│   │       │   ├── OcclusionIssue.h
│   │       │   ├── Orientation.h
│   │       │   ├── OutputMode.h
│   │       │   ├── RGBFrame.h
│   │       │   ├── RGBMark.h
│   │       │   ├── SensorIssue.h
│   │       │   ├── SkeletonData.h
│   │       │   ├── Skeleton.h
│   │       │   ├── UserFrame.h
│   │       │   ├── User.h
│   │       │   └── Vector3.h
│   │       └── utils
│   │           ├── CallbackStruct.h
│   │           └── ExceptionTranslator.h
│   └── lib
│       ├── android
│       │   ├── libmiddleware.so
│       │   ├── libnuitrack.so
│       │   ├── libOpenNI.so
│       │   └── nuitrackhelper.jar
│       ├── csharp
│       │   └── nuitrack.net.dll
│       ├── linux64
│       │   ├── libmiddleware.so
│       │   └── libnuitrack.so
│       ├── linux_arm
│       │   ├── libmiddleware.so
│       │   └── libnuitrack.so
│       ├── win32
│       │   ├── middleware.lib
│       │   └── nuitrack.lib
│       └── win64
│           ├── middleware.lib
│           └── nuitrack.lib
└── VERSION

17 directories, 65 files
```

This is the entry I've added to my `.profile` for the env var:
```bash
# Location of the Nuitrack SDK for `nuitrack-rs`.
export NUI_SDK_DIR="~/nuitrack"
```

Any ideas on what might be going on? Going out for dinner but will keep hacking at this when I get back :+1:

**Comment by mitchmindtree** [comment]
Oh, I just tried changing:
```bash
export NUI_SDK_DIR="~/nuitrack"
```
to
```bash
export NUI_SDK_DIR="/home/mindtree/nuitrack"
```
oh a whim and it worked lol!

Bash can normally handle the `"~/"` path syntax but maybe rust `Path`s cannot? Strange.
