### ISSUE TITLE
Snappy error loading recently recorded playback files

### ISSUE THREAD

**Issue by mitchmindtree** [freesig/nuitrack-rs#30]
Aye chap, I just tried running the microbe mirrors with the recordings you took on friday night but I keep getting this error:

```
thread 'nuitrack_player' panicked at 'called `Result::unwrap()` on an `Err` value: Error("snappy: corrupt input (expected valid offset but got offset 3603031332; dst position: 43968)", line: 1, column: 489328236)', src/libcore/result.rs:997:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
   9: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  10: <nuitrack_rs::Nui<nuitrack_rs::Player>>::new
  11: nuitrack_rs::playback
```

Using the master branch. Any idea why I might not be able to load these?

**Comment by mitchmindtree** [comment]
Just a note that there's a chance this could be my USB! Sometimes it signals that it's finished writing even though it's not and the file gets corrupted during ejection, so don't worry too much if you can't recreate this.

**Comment by mitchmindtree** [comment]
I'm after all the data so I can test what it's like to have the whole stream running - no worries though, I'll grab them off you in person next time and probably take some more recordings then :+1:

**Comment by freesig** [comment]
no worries, i'll bring my usb
